#!/bin/csh

cd ..
tar -cvzf coco/archives/coco.tgz coco/toolbox coco/examples coco/doc coco/README coco/LICENSE
rm -f coco/archives/coco.zip
zip -r coco/archives/coco.zip coco/toolbox coco/examples coco/doc coco/README coco/LICENSE
