#!/bin/csh

set keywords    = "Date Revision Author HeadURL Id"
set keyword_cmd = "svn propset svn:keywords"
set patterns = ( "*.c" "*.h" "*.tex" "*.m" )
set files=`svn -R list`
foreach f ( $files )
	foreach pat ( $patterns:q )
		if( "$f" =~ "$pat" ) then
			echo $keyword_cmd '"'$keywords'"' $f
			$keyword_cmd "$keywords" $f
		endif
	end
end
