function compalg_arg_check(tbid, data, dfdxhans, dfdphans, x0, p0)

assert(data.neqs~=0, '%s: insufficient number of equations', tbid);
assert(data.neqs==numel(dfdxhans), ...
  '%s: incompatible number of inputs in ''dfdxhans''', tbid);
assert(data.neqs==numel(dfdphans), ...
  '%s: incompatible number of inputs in ''dfdphans''', tbid);
assert(data.neqs==numel(x0), ...
  '%s: incompatible number of inputs in ''x0''', tbid);
assert(numel(p0)==numel(data.pnames) || isempty(data.pnames), ...
  '%s: incompatible number of elements for ''p0'' and ''pnames''', ...
  tbid);

end