function [opts bd] = bddat_append(opts, bd, sol)
%BDDAT_APPEND  Add a point at the end of the point list.
%
%   [OPTS BD] = BDDAT_APPEND(OPTS, BD) adds a point at the end of the point
%   list in opts.bd.
%
%   See also: bddat_insert, bddat_prepend
%

if strcmp(sol.pt_type, 'ROS')
	new_data = { ...
		opts.cont.branch, ...
		opts.cont.It, ...
		opts.xfunc.h, ...
		sol.pt_type, ...
		sol.lab, [], ...
		sol.p(opts.cont.op_idx(1)), ...
		norm(sol.x(opts.cont.xidx)), ...
		sol.p(opts.cont.op_idx), ...
		};
else
	new_data = { ...
		opts.cont.branch, ...
		opts.cont.It, ...
		opts.xfunc.h, ...
		sol.pt_type, ...
		sol.lab, sol.lab, ...
		sol.p(opts.cont.op_idx(1)), ...
		norm(sol.x(opts.cont.xidx)), ...
		sol.p(opts.cont.op_idx), ...
		};
end

[opts res] = coco_emit(opts, 'bddat', 'data', sol);
for i=1:size(res,1)
  new_data = [new_data res{i,2}]; %#ok<AGROW>
end

bd = [ bd ; new_data ];
