function [data J] = finitediff_DFDX(opts, data, xp)
% We are solving the problem u''+f(u,p1,p2)=0 with boundary conditions
% u(0)=u(1)=0. This function evaluates the jacobian of the residual of the
% discretized boundary value problem with respect to the elements of xp.

u = xp(data.u_idx);
p = xp(data.p_idx)';

J = [1 zeros(1,data.dim+1) 0 0;...
    zeros(1,data.dim+1) 1 0 0; ...
    data.A + data.h2 *...
    data.B * spdiags(data.f_DX(u, repmat(p, [data.dim+2, 1])), 0, ...
    data.dim+2,data.dim+2) ...
    data.h2 * data.B * ...
    data.f_DP(u, repmat(p,[data.dim+2, 1]))];

end