function hspo_arg_check(tbid, fhan, dfdxhan, dfdphan, modes, events, ...
  resets, t0, x0, p0, pnames)

assert(numel(fhan)==3, ...
  '%s: incomplete input for ''fhan''', tbid);
assert(all(cellfun('isclass', fhan, 'function_handle')), ...
  '%s: input for ''fhan'' not function handles', tbid);
assert(numel(dfdxhan)==3, ...
  '%s: incomplete input for ''dfdxhan''', tbid);
assert(numel(dfdphan)==3, ...
  '%s: incomplete input for ''dfdphan''', tbid);
nos = [numel(modes) numel(events) numel(resets) numel(t0) numel(x0)];
assert(~any(diff(nos)), ...
  '%s incompatible segment specification', tbid);
assert(numel(p0)==numel(pnames) || isempty(pnames), ...
  '%s: incompatible number of elements for ''p0'' and ''pnames''', ...
  tbid);

end